sudo: false

language: java
jdk:
  - oraclejdk8
env:
  global:
    - secure: "Fxaj73bqPrpXoN/RYrcO4RO/CS+GPlY0/j0zKHahBrESnBiXquyKOXHAojhrstHSfOs0w4DVbthyxfySeFO3kr+I0FjPMRoFGi7hP/jt6UGq3Tc0nROvUilDX0CaZfVbxO9dcAcDp+4lxJBY7hteTHzepvAa7qE1IeBqsTy4D0zdTPv4gc0JIspsIPM5JtrlxockhDAlBIbsBnQwpD4g5Hh2R0Od0+Idb+Yph7CJKsnO8dedpJLIobjpWBQT8AkGzt88lIV4gsToRGxouWhXFmk5ywuUzm96UhlLorIisHG+EN4bBn+XdUe+OG7i/Myh2Tq9a2phCkzL7W0YMxD7mLBq2FOerc90ns1DmyQIW8UXUbkeJn5Zhk1BbecD8hyt9xQfopKjO3X81pKWYVXNuzSStZ0i5NcnSEfYex6r6ciTp27DM4hHhccv4oa591YgIF83lBkk0ieg58Rc0h4V+0qAPShr7hzDN2BH/fC8BFnR+BcFargSjZGugviN5iOLFyO+u1EV7Pr1/sKTlYkdamiYtu8tXe9OZGJI+Fj9lma9zmtENLQ+50+txWrJu7q8AvOefLUck2WLVMwQ18vVFeB2IBte2KRP/OhFKiR43fyLZAl2qXX7ZTSnqPbBguG+yIagepeRsVMSB318eu+fr0TlEmkdsdK9YMtfT+taAYE="
cache:
  directories:
    - $HOME/.m2
    
script: 
  - "mvn cobertura:cobertura"
  - "mvn javadoc:javadoc"

after_success:
  - bash <(curl -s https://codecov.io/bash)
  - bash Deploy_JavaDoc.sh

notification:
  email:
    on_success: never
    on_failure: always
